FROM python:3.13

WORKDIR /src

COPY ./requirements.txt /src/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /src/requirements.txt

COPY . /src/

CMD ["fastapi", "run", "main.py", "--port", "8000"]
